spring:
  datasource:

    url: jdbc:mysql://rednorte-db-usuarios:3306/rednorte_usuarios?useSSL=false&serverTimezone=UTC
    username: user_usuarios
    password: devpassword
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

jwt:
  secret: ${JWT_SECRET:mi_secreto_super_seguro_123}
  expiration: 28800000 # 8 horas en milisegundos